services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki:/loki
    networks:
      - otelnet

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./otel/tempo-config.yaml:/etc/tempo.yaml
      - tempo:/var/tempo
    ports:
      - "3200:3200"   # Tempo UI/API
      - "4317"        # OTLP gRPC (internal for Alloy)
    networks:
      - otelnet
    

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    command: [ "-config.file=/etc/mimir.yaml" ]
    ports:
      - "9009:9009"
    volumes:
      - ./otel/mimir-config.yaml:/etc/mimir.yaml
      - mimir:/data
    networks:
      - otelnet

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345" # UI
      - "4317:4317"   # OTLP gRPC (Incoming from your Go/Python apps)
      - "4318:4318"   # OTLP HTTP (Incoming from your Go/Python apps)    
    volumes:
      - ./otel/alloy-config.river:/etc/alloy/config.alloy:ro
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - otelnet
    depends_on:
      - loki
      - tempo
      - mimir

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./otel/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - otelnet

    depends_on:
      - loki
      - tempo
      - mimir

volumes:
  loki:
  tempo:
  mimir:
  grafana-storage:

networks:
  otelnet: